### ISSUE TITLE
[QUESTION]How to use mkv_uploader

### ISSUE THREAD

**Issue by Zevolusion** [aws-samples/amazon-kinesis-video-streams-producer-embedded-c#45]
**This is a question**
A clear and concise description of what the question is.
I used mkv_uploader 
https://github.com/aws-samples/amazon-kinesis-video-streams-producer-embedded-c/tree/main/samples/mkv_uploader

But when I upload my mkv video, it only put a few seconds
Pic1 ![bc4dd4e224bb3c61aa950fa20648c31](https://user-images.githubusercontent.com/16457119/148190654-ab9b08c2-444d-44a3-bf23-3ac5ca1999a0.png)

Pic2 ![d8c06fc9c1aae204fc4f71af5eeafc5](https://user-images.githubusercontent.com/16457119/148190744-971c33d6-519f-4e89-a31c-72996a4d37c3.png)

It is 14s in Pic1, 2min in Pic2

How to fix this?

**Comment by weichihl** [comment]
In the sample code, the default value of `xTimecodeType` is `TIMECODE_TYPE_ABSOLUTE`, which means it uploads this MKV file with timestamp only based on the timestamp stored in the MKV file.
From the log, the timestamp stored in the MKV file starts from 0, which means it starts from 1970. That's why it's rejected from KVS endpoint.
You can refer to "**producer_timestamp**" in [PutMedia](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_dataplane_PutMedia.html) for details.
This sample needs some improvement to make it easier to use. But there is no specific schedule for this now.

**Comment by Zevolusion** [comment]
I got a new issue, after I set ENABLE_AUDIO_TRACK to 1 
![image](https://user-images.githubusercontent.com/16457119/149065665-2ac989d8-c2eb-47b0-a037-f228d3a04932.png)

![image](https://user-images.githubusercontent.com/16457119/149065681-5a7551ed-520b-4ea6-9740-cdcb2a3c926c.png)

but it is fine if set ENABLE_AUDIO_TRACK to 0

And  I used old version before it won't occur if I set ENABLE_AUDIO_TRACK to 1

**Comment by weichihl** [comment]
Could you pull the latest code and try "kvsapp" example? This example integrates stream buffer and KVS streaming function like the original "kvs-linux" example.

**Comment by Zevolusion** [comment]
it works thanks

**Comment by Zevolusion** [comment]
I think u should update kvs' part in 
https://github.com/aws-samples/amazon-kinesis-video-streams-media-interface
![image](https://user-images.githubusercontent.com/16457119/149122099-a6e3382f-fe2a-41f0-87a2-8ee390526956.png)
![image](https://user-images.githubusercontent.com/16457119/149122208-b12c70de-8893-4714-90c0-0e7d6c60a6f8.png)
After I set ENABLE_AUDIO_TRACK to 1

**Comment by weichihl** [comment]
The solution has been merged. Could you pull the code and try again? Thanks.

**Comment by weichihl** [comment]
@Zevolusion I'll close this issue since there are no further updates. Please feel free to reopen it if there are any other questions.
