### ISSUE TITLE
[QUESTION] How to send an end of fragment frame?

### ISSUE THREAD

**Issue by gtapizquent** [aws-samples/amazon-kinesis-video-streams-producer-embedded-c#48]
Other libraries like https://github.com/awslabs/amazon-kinesis-video-streams-producer-c
support sending end of fragment frames. But I do not see any method that readily does this.

How can this be done?

**Comment by weichihl** [comment]
I assume the end of fragment frames means the frames that haven't been sent out when it's about to terminate the connection. It can be done by checking stream buffer status and sending it out. However, there is no such feature in the sample "KvsApp," and I think it's worth adding it. 

I'll add an enhancement tag and plan to add this feature if it sounds good to you.

**Comment by weichihl** [comment]
@gtapizquent I've completed this feature in[ PR #50](https://github.com/aws-samples/amazon-kinesis-video-streams-producer-embedded-c/commit/1c46ef0a07f9b9eb58c8400436e89eb58b18a89b). Please let me know if there are any issues or features that need our help so that we can implement them in advance. Thanks.

**Comment by gtapizquent** [comment]
@weichihl Perfect. I will give this a try. You can consider the issue closed.
