### ISSUE TITLE
[QUESTION] : Libraries for ESP32-Cam using Arduino or PlatformIO

### ISSUE THREAD

**Issue by chaudhariatul** [aws-samples/amazon-kinesis-video-streams-producer-embedded-c#71]
Is there a document on how to use this Producer SDK using Arduino IDE or PlatformIO for ESP32-Cam?

**Comment by williamlai** [comment]
@chaudhariatul  I'm not pretty sure of your purpose.
* Do you want to use the camera on ESP32-Cam for video streaming? There is no H.264 hardware encoder on ESP32-Cam, so it's impossible to do that.
* If you just want to stream an existing H.264 video stream that comes from a file or an RTSP source, then it's possible. But we don't have any plan to port this library to Arduino IDE or PlatformIO.

**Comment by chaudhariatul** [comment]
@williamlai Thanks for reply!

Streaming from RTSP would have been a great with Arduino or PlatformIO.

**Comment by williamlai** [comment]
@chaudhariatul I would say there are some missing pieces of streaming from RTSP. Describe below:

* There is no major RTSP client C library that is GPL/LGPL free. The major RTSP client library like Live555 or GStreamer are both using LGPL license. We want to avoid GPL/LGPL licensed libraries so that customers can use our library without concern. There might be some RTSP client C libraries that are MIT or Apache licensed, but I haven't tried them yet.

* The memory bus performance on ESP32 might be a bottleneck. It requires lots of memory while assembling RTP packets, and it'll do many memory copies. However, ESP32's external memory is not fast enough, so it requires a mixture usage of SRAM and external RAM to have a bare performance. So if we port to Arduino or PlatformIO, it still requires some domain knowledge from the user to balance the performance by tuning the ratio of SRAM and external memory usage. But I think adjusting that against the idea of easy use of Audio IDE.

**Comment by chaudhariatul** [comment]
AWSome!
